<template>
<div class="w-full h-full bg-yellow-light">
  <div class="flex flex-col h-full justify-between">
    <div class="doco_bar_top w-full h-5"></div>
    <div class="flex flex-col justify-center items-center w-full gap-20 relative">
      <NeonMatrix :text="[String(display_time)]" :width="200" ref="neon"></NeonMatrix>
      <Comp :text="current_quesiton"></Comp>
      <div class="flex gap-5 select-none cursor-pointer">
        <div class="btn" @click="btn_skip_onclick">
          <div class="icon btn_skip"></div>
          <div class="text-3xl font-black">{{skip_count}}</div>
        </div>
        <div class="btn" @click="btn_correct_onclick">
          <div class="icon btn_correct"></div>
          <div class="text-3xl font-black">{{correct_count}}</div>
        </div>
        <div class="absolute right-0" @click="btn_reload_onclick">
          <div class="btn_reload"></div>
        </div>
      </div>
    </div>
    <div class="doco_bar_bottom w-full h-5"></div>
  </div>
</div>
</template>

<script>
import Comp from '../../components/Comp/Comp.vue'
import NeonMatrix from '../../components/NeonMatrix/NeonMatrix.vue'
export default {
  name: 'MainPage',
  components: {
    NeonMatrix,
    Comp
  },
  data: function () {
    return {
      display_time: 180,
      correct_count: 0,
      skip_count: 0,
      q_list: ['春秋',
        '老子',
        '孔子',
        '齐桓公',
        '夫差',
        '勾践',
        '战国',
        '廉颇',
        '蔺相如',
        '赵括',
        '庄子',
        '墨子',
        '孟子',
        '荆轲',
        '商鞅',
        '屈原',
        '扁鹊',
        '秦',
        '嬴政',
        '赵高',
        '项羽',
        '汉',
        '刘邦',
        '萧何',
        '韩信',
        '张良',
        '司马相如',
        '卓文君',
        '司马迁',
        '李广',
        '王昭君',
        '董卓',
        '贾谊',
        '张仲景',
        '三国',
        '曹操',
        '刘备',
        '孙权',
        '吕布',
        '关羽',
        '张飞',
        '诸葛亮',
        '周瑜',
        '曹植',
        '吕蒙',
        '晋',
        '潘岳',
        '左思',
        '王羲之',
        '谢安',
        '谢道韫',
        '陶渊明',
        '南北朝',
        '郦道元',
        '萧统',
        '谢灵运',
        '祖冲之',
        '唐',
        '李渊',
        '李世民',
        '魏征',
        '房玄龄',
        '杜如晦',
        '秦琼',
        '武则天',
        '李隆基',
        '杨玉环',
        '王勃',
        '陈子昂',
        '王之涣',
        '安禄山',
        '史思明',
        '李白',
        '高力士',
        '杜甫',
        '白居易',
        '王维',
        '孟浩然',
        '杜牧',
        '李商隐',
        '李林甫',
        '高适',
        '王昌龄',
        '孙思邈',
        '玄奘',
        '鉴真',
        '狄仁杰',
        '黄巢',
        '文成公主',
        '松赞干布',
        '贺知章',
        '韩愈',
        '柳宗元',
        '宋',
        '赵匡胤',
        '林逋',
        '包拯',
        '范仲淹',
        '司马光',
        '欧阳修',
        '苏洵',
        '苏轼',
        '苏辙',
        '王安石',
        '曾巩',
        '宋江',
        '方腊',
        '岳飞',
        '秦桧',
        '赵构',
        '朱熹',
        '柳永',
        '黄庭坚',
        '秦观',
        '晏殊',
        '陆游',
        '辛弃疾',
        '李清照',
        '文天祥',
        '元',
        '铁木真',
        '忽必烈',
        '关汉卿',
        '王实甫',
        '马致远',
        '明',
        '朱元璋',
        '宋濂',
        '朱允炆',
        '朱棣',
        '郑和',
        '解缙',
        '唐寅',
        '文征明',
        '冯梦龙',
        '吴承恩',
        '汤显祖',
        '戚继光',
        '海瑞',
        '李时珍',
        '徐霞客',
        '宋应星',
        '王守仁',
        '张居正',
        '柳如是',
        '徐渭',
        '清',
        '皇太极',
        '康熙',
        '雍正',
        '乾隆',
        '纪晓岚',
        '林则徐',
        '洪秀全',
        '光绪',
        '宣统',
        '慈禧',
        '曾国藩',
        '李鸿章',
        '张之洞',
        '曹雪芹',
        '吴敬梓',
        '鲁迅',
        '张爱玲',
        '沈从文',
        '曹禺',
        '老舍',
        '巴金',
        '钱钟书',
        '余华',
        '莫言',
        '刘慈欣',
        '姚明',
        '郎平',
        '林丹',
        '马龙',
        '苏炳添',
        '马云',
        '马化腾',
        '雷军',
        '张一鸣',
        '任正非',
        '张国荣',
        '胡歌',
        '邓超',
        '肖战',
        '王传君',
        '那英',
        '周杰伦',
        '张杰',
        '林俊杰',
        '凤凰传奇',
        '柏拉图',
        '达.芬奇',
        '莎士比亚',
        '牛顿',
        '亚当.斯密',
        '拿破仑',
        '贝多芬',
        '达尔文',
        '伦琴',
        '弗莱明',
        '爱迪生',
        '弗洛伊德',
        '莱特兄弟',
        '居里夫人',
        '爱因斯坦',
        '霍金',
        '比尔盖茨',
        '乔布斯',
        '扎克伯格',
        '特朗普',
        '一心一意',
        '爱不释手',
        '杯弓蛇影',
        '不言而喻',
        '草木皆兵',
        '川流不息',
        '鼎力相助',
        '东奔西走',
        '风雨无阻',
        '改过自新',
        '画蛇添足',
        '画龙点睛',
        '井井有条',
        '如虎添翼',
        '胜友如云',
        '喜闻乐见',
        '不屈不挠',
        '沉默寡言',
        '拔苗助长',
        '物美价廉',
        '不可思议',
        '因小失大',
        '临危不惧',
        '口耳相传',
        '目无全牛',
        '饮水思源',
        '返回归正',
        '喜气洋洋',
        '眼花缭乱',
        '守口如瓶',
        '求同存异',
        '一帆风顺',
        '势如破竹',
        '笨鸟先飞',
        '移花接木',
        '同心协力',
        '形影不离',
        '宁死不屈',
        '继往开来',
        '举一反三',
        '明目张胆',
        '再接再励',
        '长久之计',
        '统统镇压',
        '先发制人',
        '独树一帜',
        '高瞻远瞩',
        '黔驴技穷',
        '一见钟情',
        '上天入地',
        '不约而同',
        '指鹿为马',
        '名列前茅',
        '有的放矢',
        '鞠躬尽瘁',
        '剖析问题',
        '相敬如宾',
        '乐善好施',
        '夜以继日',
        '桃李满天下',
        '异想天开',
        '剩女剩男',
        '乘风破浪',
        '安然无恙',
        '飞黄腾达',
        '不胫而走',
        '勇往直前',
        '不堪回首',
        '高人一等',
        '疾风知劲草',
        '行尸走肉',
        '青出于蓝',
        '没有理由',
        '明日黄花',
        '鳏夫鳏妇',
        '一言九鼎',
        '头头是道',
        '河东狮吼',
        '拦路虎',
        '心中有数',
        '大公无私',
        '买椟还珠',
        '否极泰来',
        '千钧一发',
        '否极泰来',
        '囫囵吞枣',
        '竹报平安',
        '无可奈何',
        '舍己为人',
        '不以为然',
        '鱼龙混杂',
        '深思熟虑',
        '心心相印',
        '万事如意',
        '一清二白',
        '不忘初心',
        '萍水相逢',
        '高来高去',
        '冷若冰霜',
        '迎刃而解',
        '一鼓作气',
        '义不容辞',
        '别具匠心',
        '乐天知命',
        '财源广进',
        '走南闯北',
        '不辞而别',
        '船到桥头自然直',
        '风靡一时',
        '举足轻重',
        '见义勇为',
        '精益求精',
        '不屈不挠',
        '绳锯木断',
        '一诺千金',
        '精疲力竭',
        '同舟共济',
        '名副其实',
        '风平浪静',
        '同仇敌忾',
        '达官要人',
        '知人善任',
        '指桑骂槐',
        '不可多得',
        '以身作则',
        '直截了当',
        '精明能干',
        '义无反顾',
        '实事求是',
        '一视同仁',
        '不屈不挠',
        '岁月如歌',
        '眼睁睁地',
        '技高一筹',
        '挥金如土',
        '言传身教',
        '津津乐道',
        '雪中送炭',
        '见仁见智',
        '兵不厌诈',
        '一丝不苟',
        '大公无私',
        '得心应手',
        '百折不挠',
        '鹤立鸡群',
        '谋事在人',
        '一览无余',
        '强词夺理',
        '炙手可热',
        '三心二意',
        '杯水车薪',
        '卧虎藏龙',
        '伟业所成',
        '世界之大',
        '一言难尽',
        '了如指掌',
        '大义凛然',
        '拔刀相助',
        '一丝不苟',
        '千锤百炼',
        '取长补短',
        '灵活应变',
        '井底之蛙',
        '书香门第',
        '启发思维',
        '指日可待',
        '醉翁之意',
        '海阔天空',
        '日新月异',
        '溜之大吉',
        '守口如瓶',
        '高耸入云',
        '乘风归来',
        '望尘莫及',
        '生龙活虎',
        '行动如风',
        '持之以恒',
        '安然无恙',
        '不堪设想',
        '无懈可击',
        '不敢托大',
        '鸟语花香',
        '是非之地',
        '幸灾乐祸',
        '一言为定',
        '立竿见影',
        '风声雨声',
        '再接再厉',
        '上天眷顾',
        '高山仰止',
        '挥洒自如',
        '古道热肠',
        '明哲保身',
        '大手大脚',
        '不辞而别',
        '藏龙卧虎',
        '见者有份',
        '画龙点睛',
        '《简·爱》',
        '《活着》',
        '《飘》',
        '《平凡的世界》',
        '《雷雨》',
        '《巴黎圣母院》',
        '《安妮日记》',
        '《百年孤独》',
        '《红楼梦》',
        '《月亮和六便士》',
        '《明朝那些事儿》',
        '《时间简史》',
        '《曾国藩传》',
        '《史记》',
        '《三国演技》',
        '《西游记》',
        '《钢铁是怎样炼成的》',
        '《变形记》',
        '《论语》',
        '《水浒传》',
        '《堂吉诃德》',
        '《哈姆雷特》',
        '《罪与罚》',
        '《茶花女》',
        '《孙子兵法》',
        '《周易》',
        '《春秋》',
        '《老子》',
        '《诗经》',
        '《孟子》',
        '《骆驼祥子》',
        '《永乐大典》',
        '《呐喊》',
        '《鹿鼎记》',
        '《资治通鉴》',
        '《三字经》',
        '《阳明全书》',
        '《聊斋志异》',
        '《围城》',
        '《本草纲目》',
        '《水经注》',
        '《傲慢与偏见》',
        '《双城记》',
        '《童年》',
        '《汉谟拉比法典》',
        '《羊脂球》',
        '《马可·波罗游记》',
        '《悲惨世界》',
        '《战争论》',
        '《圣经》',
        '《沉思录》',
        '《无畏的希望》',
        '《倾城之恋》',
        '《呼兰河传》',
        '《长恨歌》',
        '《黄金时代》',
        '《追求卓越》',
        '《道德经》',
        '《压力测试》',
        '《商业历险记》',
        '《麦田里的守望者》',
        '《老人与海》',
        '《理想国》',
        '《愤怒的葡萄》',
        '《战争与和平》',
        '《了不起的盖茨比》',
        '《肖申克的救赎》',
        '《谁动了我的奶酪》',
        '《阿甘正传》',
        '《士兵突击》',
        '《把信送给加西亚》',
        '《人生论》',
        '《荀子》',
        '《颜氏家训》',
        '《曾国藩家书》',
        '《贝多芬传》',
        '《富兰克林》',
        '《人性的弱点》',
        '《鬼谷子》',
        '《厚黑学》',
        '《战国策》',
        '《韩非子》',
        '《智慧书》',
        '《家范》',
        '《菜根谭》',
        '《 1984 》',
        '《美声》',
        '《天生就会跑》',
        '《远大前程》',
        '《冷血》',
        '《哈利波特与魔法石》',
        '《看不见的人》',
        '《生命不息》',
        '《草原小屋》',
        '《纯真年代》',
        '《饥饿游戏》',
        '《小王子》',
        '《阿Q正传》',
        '《三十六计》',
        '《国富论》',
        '《物种起源》',
        '《源氏物语》',
        '《红与黑》',
        '《神曲》',
        '《实用主义》'],
      skip_index: [],
      current_quesiton: ''
    }
  },
  methods: {
    get_next_question: function () {
      const ran = Math.floor(Math.random() * this.q_list.length)
      if (this.skip_index.includes(ran)) {
        return this.get_next_question()
      } else {
        this.skip_index.push(ran)
      }
      console.log(ran)
      return this.q_list[ran]
    },
    btn_skip_onclick: function () {
      this.current_quesiton = this.get_next_question()
      this.skip_count += 1
    },
    btn_correct_onclick: function () {
      this.current_quesiton = this.get_next_question()
      this.correct_count += 1
    },
    btn_reload_onclick: function () {
      this.current_quesiton = this.get_next_question()
      this.correct_count = 0
      this.skip_count = 0
      this.$refs.neon.reset_num()
    }
  },
  mounted () {
    this.current_quesiton = this.q_list[0]
    this.skip_index.push(0)
  }
}
</script>

<style lang="less" scoped>
.doco_bar_top{
  background: linear-gradient(#ffa500,#FEF6E8);
}
.doco_bar_bottom{
  background: linear-gradient(#FEF6E8,#ffa500);
}
.btn{
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100px;
  width: 100px;
  border-radius: 10px;
  border: solid 3px #ffa500;
  background: #FEF6E8;
}
.btn_correct{
  background-color: rgba(255,255,255,0.2);
  background-image: url(./res/img/correct.svg);
  background-size: contain;
  background-repeat: no-repeat;
}
.btn_reload{
  height: 30px;
  width: 30px;
  background-color: rgba(255,255,255,0.2);
  background-image: url(./res/img/reload.svg);
  background-size: contain;
  background-repeat: no-repeat;
}
.btn_skip{
  background-color: rgba(255,255,255,0.2);
  background-image: url(./res/img/skip.svg);
  background-size: contain;
  background-repeat: no-repeat;
}
.icon{
  height: 50px;
  width: 50px;
}
</style>

